### ISSUE TITLE
generateOpenApi cannot handle duplicate routes

### ISSUE THREAD

**Issue by scarf005** [ts-rest/ts-rest#313]
## example code
```ts
export const contract = c.router({
  likes: likesContract,
  reviews: reviewsContract,
})

export const likesContract = c.router({
    post: {
      method: 'POST',
      path: '/:bookInfoId/like',
      // ...
    },
  })

export const reviewsContract = c.router({
  post: {
    method: 'POST',
    path: '/',
  // ...
 }
})
```
throws `Route 'post' already defined under likes` when i try to use `@ts-rest/openapi`:

<details><summary>Error log</summary>

```
2023-07-23 11:42:13:4213 error: uncaughtException: Route 'post' already defined under likes
Error: Route 'post' already defined under likes
    at /home/scarf/repo/lib42/backend/node_modules/.pnpm/@ts-rest+open-api@3.26.4_@ts-rest+core@3.26.4_zod@3.21.4/node_modules/@ts-rest/open-api/index.js:104:23
    at Array.reduce (<anonymous>)
    at generateOpenApi (/home/scarf/repo/lib42/backend/node_modules/.pnpm/@ts-rest+open-api@3.26.4_@ts-rest+core@3.26.4_zod@3.21.4/node_modules/@ts-rest/open-api/index.js:99:30)
    at Object.<anonymous> (/home/scarf/repo/lib42/backend/backend/src/app.ts:66:32)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module.m._compile (/home/scarf/repo/lib42/backend/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.1_typescript@5.1.6/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Object.require.extensions.<computed> [as .ts] (/home/scarf/repo/lib42/backend/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.1_typescript@5.1.6/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Function.Module._load (node:internal/modules/cjs/loader:962:12)
 Error Stack: Error: Route 'post' already defined under likes
    at /home/scarf/repo/lib42/backend/node_modules/.pnpm/@ts-rest+open-api@3.26.4_@ts-rest+core@3.26.4_zod@3.21.4/node_modules/@ts-rest/open-api/index.js:104:23
    at Array.reduce (<anonymous>)
    at generateOpenApi (/home/scarf/repo/lib42/backend/node_modules/.pnpm/@ts-rest+open-api@3.26.4_@ts-rest+core@3.26.4_zod@3.21.4/node_modules/@ts-rest/open-api/index.js:99:30)
    at Object.<anonymous> (/home/scarf/repo/lib42/backend/backend/src/app.ts:66:32)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module.m._compile (/home/scarf/repo/lib42/backend/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.1_typescript@5.1.6/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Object.require.extensions.<computed> [as .ts] (/home/scarf/repo/lib42/backend/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.16.1_typescript@5.1.6/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Function.Module._load (node:internal/modules/cjs/loader:962:12)
```

</details> 

I'm not sure whether it's a bug or an intended behavior as they are already specified by their object path and url like:

| path | url |
|--------|--------|
| `likes.post` | `reviews.post` |
| `/:bookInfoId/like` | `/` |

**Comment by scarf005** [comment]
my bad, i've set `setOperationId: true` which obviously only works on unique routes.

https://ts-rest.com/docs/open-api#enabling-operationids-recommended

tho it'd be nice to also have an option to create operationid by concatenating router path like `likes.post` -> `likesPost`
