### ISSUE TITLE
ts-rest/express throws TypeError when createExpressEndpoints is called with a router that relies on an instance of a class to satisfy API contract

### ISSUE THREAD

**Issue by laser** [ts-rest/ts-rest#386]
When creating a router, if an instance of a class is used to satisfy the API contract and that class has properties (private or otherwise), ts-rest/express will throw a `TypeError` when `createExpressEndpoints` is called.

For example:

```ts
import { ServerInferRequest, ServerInferResponses, initContract } from '@ts-rest/core';
import { createExpressEndpoints, initServer } from '@ts-rest/express';
import { z } from 'zod';
import express from 'express';

export const EchoSchema = initContract().router({
  echo: {
    method: 'POST',
    path: '/echo',
    body: z.object({
      call: z.string(),
    }),
    responses: {
      201: z.object({
        response: z.string(),
      }),
    },
  },
});

class EchoController {
  private logger: (msg: string) => void;

  constructor(logger: (msg: string) => void) {
    this.logger = logger;
  }

  public async echo(
    req: ServerInferRequest<typeof EchoSchema>['echo'],
  ): Promise<ServerInferResponses<typeof EchoSchema>['echo']> {
    this.logger(`echoing: ${req.body.call}`);

    return {
      status: 201,
      body: {
        response: `you said: ${req.body.call}`,
      },
    };
  }
}

const app = express();
app.use(express.urlencoded({ extended: false }));
app.use(express.json());

const logger = (msg: string) => console.log(msg);

const router = initServer().router(EchoSchema, new EchoController(logger));

createExpressEndpoints(EchoSchema, router, app);

const host = '127.0.0.1';
const port = 8888;

console.log(`starting server: host=${host}, port=${port}`);

app.listen(port, host);
```

Running that code will produce the following error:

```shell
/opt/homebrew/bin/node --require ts-node/register /tmp/someapp/src/index.ts
/tmp/someapp/node_modules/@ts-rest/core/index.js:70
    return 'method' in obj && 'path' in obj;
                    ^
TypeError: Cannot use 'in' operator to search for 'method' in undefined
    at Object.isAppRoute (/tmp/someapp/node_modules/@ts-rest/core/index.js:70:21)
    at recursivelyApplyExpressRouter (/tmp/someapp/node_modules/@ts-rest/express/index.js:41:19)
    at recursivelyApplyExpressRouter (/tmp/someapp/node_modules/@ts-rest/express/index.js:32:13)
    at createExpressEndpoints (/tmp/someapp/node_modules/@ts-rest/express/index.js:185:5)
    at Object.<anonymous> (/tmp/someapp/src/index.ts:50:23)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module.m._compile (/tmp/someapp/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Object.require.extensions.<computed> [as .ts] (/tmp/someapp/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)

Process finished with exit code 1
```

One can work around _that_ particular `TypeError` by marking the property as non-enumerable (using `Object.defineProperty`) or by editing the ts-rest/core/index.js file to do something like `if (!schema[key]) continue`, but both result in an application that responds to no inbound HTTP requests because `initializeExpressRoute` won't be called.

**Comment by Gabrola** [comment]
We never intended for class instances to be supplied in place of a router, only plain objects.

**Comment by laser** [comment]
In case someone other than me runs into this issue, a simple workaround is to pass (to the `router` call) an object literal containing a bunch of references to the methods on an instance of your class. It's not elegant, but it is type-safe:

```ts
const controller = new EchoController(logger);
const router = initServer().router(EchoSchema, { echo: controller.echo });
```

We use method decorators to abstract away various annoyances (caching, logging, context propagation) and do dependency injection in our constructors, so an approach that works with classes is a must (for us).

Thanks again for the great library!

**Comment by Gabrola** [comment]
@laser thanks for the update! Don't forget to bind your instance `controller.echo.bind(controller)` :)

**Comment by laser** [comment]
Oops - good call. I've updated my example as per your feedback.
