### ISSUE TITLE
@ts-rest/serverless Cannot use NextJS redirect() function

### ISSUE THREAD

**Issue by gcmarcello** [ts-rest/ts-rest#720]
### Describe the bug

Using redirect() function inside a route throws an error (as NextJS should do, according to its documentation). The redirection due to that, does not happen.

[Link to the documentation - Next Redirect](https://nextjs.org/docs/app/building-your-application/routing/redirecting#redirect-function)

### How to reproduce

1. Create the router (and a contract, but not relevant in this case)
```typescript
export const authRouter = tsr.router(authContract, {
  login: async ({ body }) => {
    await service.login(body);

    return redirect("/");
  },
 
});
```

2. Create a handler using createNextHandler
```typescript
export const handler = createNextHandler(
  {
    auth: authContract,
  },
  {
    auth: authRouter,
  },
  {
    basePath: "/api/",
    jsonQuery: true,
    responseValidation: true,
    handlerType: "app-router",
    errorHandler: async (error) => {
      console.log(error);
      try {
        if (error instanceof RequestValidationError) {
          throw {
            status: 400,
            body: error.message,
          };
        }
        if (error instanceof TsRestResponseError)
          throw {
            status:
              ("status" in (error as any) && (error as any).status) || 500,
            body: "Internal server error",
          };
      } catch (error) {
        console.log(error);
      }
    },
  }
);
```

3. Executing the route returns the NEXT_REDIRECT error, as expected.
``` 
[ts-rest] Unexpected error... Error: NEXT_REDIRECT
    at getRedirectError (/workspaces/ts-rest-project/.next/server/chunks/93c34_next_5e4da3._.js:10856:19)
    at redirect (/workspaces/ts-rest-project/.next/server/chunks/93c34_next_5e4da3._.js:10863:11)
    at login (/workspaces/ts-rest-project/.next/server/chunks/[root of the server]__cfc1ca._.js:1178:426)
    at async routeHandler (/workspaces/ts-rest-project/.next/server/chunks/node_modules__pnpm_9d5008._.js:3941:30)
    at async Object.fetch (/workspaces/ts-rest-project/.next/server/chunks/node_modules__pnpm_9d5008._.js:3300:54)
    at async AppRouteRouteModule.do (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:33313)
    at async AppRouteRouteModule.handle (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40382)
    at async doRender (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/base-server.js:1455:42)
    at async responseGenerator (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/base-server.js:1814:28)
    at async DevServer.renderToResponseWithComponentsImpl (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/base-server.js:1824:28)
    at async DevServer.renderPageComponent (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/base-server.js:2240:24)
    at async DevServer.renderToResponseImpl (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/base-server.js:2278:32)
    at async DevServer.pipeImpl (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/base-server.js:960:25)
    at async NextNodeServer.handleCatchallRenderRequest (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/next-server.js:281:17)
    at async DevServer.handleRequestImpl (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/base-server.js:853:17)
    at async /workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/dev/next-dev-server.js:373:20
    at async Span.traceAsyncFn (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/trace/trace.js:153:20)
    at async DevServer.handleRequest (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/dev/next-dev-server.js:370:24)
    at async invokeRender (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/lib/router-server.js:183:21)
    at async handleRequest (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/lib/router-server.js:360:24)
    at async requestHandlerImpl (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/lib/router-server.js:384:13)
    at async Server.requestListener (/workspaces/ts-rest-project/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96_fpy4of67lljj5mmtr3hdr3usnm/node_modules/next/dist/server/lib/start-server.js:142:13)```





### Expected behavior

Ts-Rest should identify that this in fact an "error" caused by redirect() function (maybe using the isRedirectError() function provided by Next) and properly redirect the user to the path indicated


### Code reproduction

Link to the repo with the error reproduction:

https://github.com/gcmarcello/ts-rest-next-redirect

### ts-rest version

```json
"@ts-rest/core": "^3.51.0",
"@ts-rest/react-query": "^3.51.0",
"@ts-rest/serverless": "^3.51.0",
```

**Comment by suhailopensource** [comment]
Hi @oliverbutler , I looked into this and I think Ive found the root cause — happy to pick it up.

`createNextHandler` (app router) runs through the shared serverless router in
`libs/ts-rest/serverless/src/lib/router.ts`. Next's `redirect()` works by *throwing*
an error whose digest starts with `NEXT_REDIRECT`, which Next's own boundary is
supposed to catch and turn into the actual redirect.

The problem is that ts-rest catches it first:

- the inner `try/catch` around the handler only special-cases `TsRestResponseError`
  and re-throws everything else;
- the outer `errorHandler` then wraps any non-`TsRestHttpError` as a generic 500 and
  serializes it into a `TsRestResponse`.

So the `NEXT_REDIRECT` error never propagates back to Next, and you get a 500-ish
response instead of a redirect. There's no `NEXT_REDIRECT` / `isRedirectError` check
anywhere in the path.

Proposed fix: detect the redirect error and re-throw it so Next can handle it,
ideally in the Next adapter (`ts-rest-next.ts`) so the core router stays
framework-agnostic. To avoid depending on Next's private `next/dist/...`
`isRedirectError` import (which moves between Next versions), I'd match on the error
shape instead, roughly:

```ts
if (e && typeof (e as any).digest === 'string' &&
    (e as any).digest.startsWith('NEXT_REDIRECT')) {
  throw e; // let Next handle the redirect
}

**Comment by suhailopensource** [comment]
I''ll add a test based on @gcmarcello  reproduction. Could this be assigned to me?
I should be able to open a PR today or tomorrow.
